### ISSUE TITLE
BNode style start node is opaque in error reporting

### ISSUE THREAD

**Issue by hsolbrig** [hsolbrig/PyShEx#34]
When the start node is a BNode:

```start=@<Observation> AND {fhir:nodeRole [fhir:treeRoot]}```

The error reporting just shows the BNode:
```
Errors:
  Focus: http://hl7.org/fhir/Observation/example-haplotype2
  Start: N37a8da033a1946dfbd86fe2fd8d4ceef
  Reason:   ...
```
There should be some way to show at least part of the actual ShEx or make the label less opaque.
