### ISSUE TITLE
Error reporting doesn't provide enough info when it comes to BNodes

### ISSUE THREAD

**Issue by hsolbrig** [hsolbrig/PyShEx#35]
The message:
```
Errors:
  Focus: http://hl7.org/fhir/Observation/example-haplotype2
  Start: N37a8da033a1946dfbd86fe2fd8d4ceef
  Reason:   Datatype constraint (http://www.w3.org/2001/XMLSchema#string) on BNode
```
doesn't carry enough information to know what really happened
